local ffi = require("ffi")

local log = ck.log.new('objects/critters.lua')
local utils = require('ck.system.utils')

local CritterClass = require('ck.fallout2.classes.critter')
local CritterProto = require('ck.fallout2.classes.critter_proto')
local map          = require('ck.fallout2.map')
local stats        = require('ck.fallout2.objects.critters.stats')
local skills       = require('ck.fallout2.objects.critters.skills')

local critters = {}

-- Each lua-created critter has a tag (to keep his state)
-- Tag is being autogenerated for critters that were spawned without explit tag
critters.spawn_counters = {}

function critters.reset_spawn_counters()
  logger.debug("spawn counters reset")
  critters.spawn_counters = {}
end

function critters.reset_spawn_counters_for_mod(mod_id)
  logger.debug("spawn counters reset for %s", mod_id)

  local mod_counters = critters.spawn_counters[mod_id]
  if mod_counters then critters.spawn_counters[mod_id] = 0 end
end

function critters.generate_unique_tag(mod_id)
  local current_index = critters.spawn_counters[mod_id] or 0

  critters.spawn_counters[mod_id] = current_index + 1

  return "spawn_" .. mod_id .. "_" .. current_index
end

-- Allocates critter prototype
-- It lives only in a context of a map and is erased by fallout2-ce on map transitions/game loads
function critters.allocate_prototype(pid, config)
  local proto_name = not utils.is_blank(config.name) and config.name or nil
  local proto_description = not utils.is_blank(config.description) and config.description or nil
  local ai_packet  = not utils.is_blank(config.ai_packet) and config.ai_packet or nil

  local proto_params = ffi.new("CritterLuaProtoParams", {
    name = proto_name,
    description = proto_description,
    ai_packet = ai_packet,
  })

  local allocated_pid = ffi.C.ck_critter_allocate_prototype(pid, proto_params)

  return CritterProto.new(allocated_pid, proto_name, proto_description, ai_packet)
end

--- args tracer
local ck_critter_spawn_traced = utils.trace("FFI:ck_critter_spawn", ffi.C.ck_critter_spawn)
function critters.register(tag, pid, tile, config)
  local mod_id = ffi.string(ffi.C.ck_get_current_mod_id())

  -- Check if tag is blank, treat it as nil
  if tag and utils.is_blank(tag) then tag = nil end

  -- spawn params
  local spawn_params = ffi.new("CritterLuaSpawnParams", {
    tag = tag or critters.generate_unique_tag(mod_id),
    elevation = config.elevation or ffi.C.ck_current_elevation(),
    script_index = config.script_index or -1,
    team = config.team or -1
  })

  -- proto params (custom proto_name/description etc)
  local proto_name = not utils.is_blank(config.name) and config.name or nil
  local proto_description = not utils.is_blank(config.description) and config.description or nil
  local ai_packet  = not utils.is_blank(config.ai_packet) and config.ai_packet or nil
  local team_id = config.team or -1

  local proto_params = ffi.new("CritterLuaProtoParams", {
    name = proto_name, description = proto_description, ai_packet = ai_packet, team = team_id
  })

  local lua_id  = ck_critter_spawn_traced(pid, tile, spawn_params, proto_params)

  if lua_id == -1 then
    log.warn("Failed to register critter (FFI) (tag: %s)", lua_tag)
    return nil
  end

  if lua_id == -2 then
    log.debug("Critter %s is dead and has default prototype name/description", lua_tag)
    return nil
  end

  return CritterClass.new(lua_id, config)
end

function critters.create(pid, tile, config)
  local spawn_params = {}
  spawn_params.elevation    = config.elevation or 0
  spawn_params.script_index = config.script_index or -1
  spawn_params.team         = config.team or -1
  -- This is used for critters without explicitly specified tag
  -- critters.spawn automatically generates spawn_{index} tag (without custom prototype)
  return critters.register(nil, pid, tile, spawn_params)
end

return critters
